In [2]:
import numpy as np
array = np.array([1,2,3,4,5])

print(array , type(array))



[1 2 3 4 5] <class 'numpy.ndarray'>


In [13]:
arr1 = np.zeros([2,3])
print(arr1)

print("\n")

arr2 = np.ones((2,5))
print(arr2)

arr3 = np.eye(3)
print(arr3)




[[0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
arr = np.array([[1,2,3],[4,5,6],[8,9,10],[5,2,5]])
print(type(arr), arr.shape, arr)

reshape_arr = arr.reshape((3,4))
print(reshape_arr, reshape_arr.shape)

<class 'numpy.ndarray'> (4, 3) [[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]
 [ 5  2  5]]
[[ 1  2  3  4]
 [ 5  6  8  9]
 [10  5  2  5]] (3, 4)
